---
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.15', '1.16']
    container: golang:${{ matrix.go-version }}-alpine
    steps:
      - uses: actions/checkout@v2
      - run: test -z "$(gofmt -l .)"
      - run: go test -cover -v ./...
